services:
  template-azure-python:
    container_name: template-azure-python
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PROJECT_NAME: hello
    ports:
      - "8000:8000"
