from typing import Protocol

from template_azure_python.domain import Task, TaskId


class TaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...

    async def get(self, task_id: TaskId) -> Task | None: ...

    async def list(self) -> tuple[Task, ...]: ...

    async def update(self, task: Task) -> bool: ...

    async def delete(self, task_id: TaskId) -> bool: ...
